endpoints:
  lookupService:
    url: https://testabc.free.beeceptor.com/lookup
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.connexta.transformation.service: DEBUG